import Head from 'next/head';
import Table from 'react-bootstrap/Table';

import 'bootstrap/dist/css/bootstrap.min.css';
import { useEffect, useState } from 'react';
import { Container } from 'react-bootstrap';

export default function Home() {
	const [data, setData] = useState([]);
	useEffect(() => {
		const fetchData = async () => {
			try {
				const response = await fetch(
					`https://13.61.215.183/api/fetch-result-direct`,
					{
						headers: {
							'Content-Type': 'application/json',
						},
					}
				);

				if (!response.ok) {
					throw new Error(`HTTP error! Status: ${response.status}`);
				}

				const result = await response.json();
				setData(result.data); // Adjust this if your data path is different
			} catch (error) {
				console.error('Fetch error:', error);
			}
		};

		fetchData();
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Container style={{ justifyContent: 'center', alignItems: 'center' }}>
				<Table
					striped
					bordered
					hover>
					<thead>
						<tr>
							<th>CategoryName</th>
							<th>Number</th>
						</tr>
					</thead>
					<tbody>
						{data.map((item, index) => (
							<tr>
								<td>{item.categoryname}</td>
								<td>{item.number}</td>
							</tr>
						))}
					</tbody>
				</Table>
			</Container>
		</>
	);
}
